# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    name: Tests & Benchmarks

    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        go: ["1.24.x", "1.23.x", "1.22.x", "1.21.x", "1.20.x", "1.19.x", "1.18.x", "1.17.x", "1.16.x", "1.15.x", "1.14.x", "1.13.x"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Test
      run: go test -v ./...

    - name: Benchmarks
      run: go test -bench=. ./...
